### ISSUE TITLE
bigWig in binary code

### ISSUE THREAD

**Issue by DannyBerg** [bowhan/piPipes#10]
Hey i was using the piPipes small, and in the  output folder 'bigWig_normalized_by_mirna' all the bigwig files are in binary code. 
Can u make the output in standard utf-8 or something?
Thank you

**Comment by bowhan** [comment]
Hi
bigWig files are in binary by nature. You can load it into UCSC genome browser or IGV directly. They are indexed binaries to allows fast random access by machine, not by human.

Please find more information here.
http://genome.ucsc.edu/goldenpath/help/bigWig.html
