### ISSUE TITLE
TRANSGENE_MAPPING_DIR not set in piPipes_GenomeSeq.sh

### ISSUE THREAD

**Issue by blaiseli** [bowhan/piPipes#11]
Dear Bo Han,

I tried to run the `piPipes dna` pipeline and noticed the following in the output:
```
[bam_parse_region] fail to determine the sequence name.
[main_samview] region "chrXHet:-29-971" specifies an unknown reference name. Continue anyway.
[2015-09-17 11:49:00 CEST] Mapping transgene insertion by TEMP
piPipes_GenomeSeq.sh: line 291: /transgene.genome.bed: Permission denied
[samopen] SAM header is present: 15 sequences.
(ERR): bowtie2-align exited with value 141
```

Looking at `piPipes_GenomeSeq.sh`, it seems that the "Permission denied" error is due to the fact that line 109 (of current version) is commented:
```
# TRANSGENE_MAPPING_DIR=transgene_mapping && mkdir -p $TRANSGENE_MAPPING_DIR
```

This variable not being defined make it impossible for `bedtools_piPipes bamtobed` (line 291) to write its output`: $TRANSGENE_MAPPING_DIR/transgene.genome.bed` is just `/transgene.genome.bed`, and consequently not writeable.

**Comment by bowhan** [comment]
Hi,
Thank you very much for reporting this bug. It has been fixed.
