### ISSUE TITLE
gene_transposon_cluster_direct_mapping is absent from piPipes rna output

### ISSUE THREAD

**Issue by blaiseli** [bowhan/piPipes#13]
The documentation for the RNA-Seq pipeline (<https://github.com/bowhan/piPipes/wiki/RNA-seq>) mentions a `gene_transposon_cluster_direct_mapping` directory that is not present in the output of `piPipes rna`.

**Comment by bowhan** [comment]
I will need more information to debug. 
Can you please run `piPipes_debug` (instead of `piPipes`) in a new, clean directory and attach the stdout and stderr?
Thank you!

**Comment by blaiseli** [comment]
Hi,

I ran using piPipes_debug as you suggested.

You can find the logs here:
stdout: http://www.normalesup.org/~bli/cn_bw_piPipes_rna.log
stderr: http://www.normalesup.org/~bli/cn_bw_piPipes_rna.err

The output directory contains the following:
```
rRNA_mapping/
input_read_files/
cn_bw_.basic_stats
cufflinks_output/
bigWig/
htseq_count/
genome_mapping/
pdfs/
direct_transcriptome_mapping/
```

Hope this helps.

**Comment by bowhan** [comment]
Actually `gene_transposon_cluster_direct_mapping` has been replaced by `direct_transcriptome_mapping` so you are fine. The Wiki needs to be updated.
And "cluster" has been removed from the transcriptome index (leaving only gene mRNA and transposon consensus sequences). The reason to use consensus sequence is to avoid multi-mappers and incorporating cluster sequences is against this purpose. Plus, there is little evidence that dual-strand clusters are transcribed as a whole.
