### ISSUE TITLE
problem with piPipes installation on OSx

### ISSUE THREAD

**Issue by mpetit75** [bowhan/piPipes#15]
Hi,

I installed everything require for the piPipes running following the wiki you made. I even test the installation on a Macbook pro with another OS version, but I still got the same message on my terminal when I want to test if piPipes is correctly installed.
Can you help me with this issue?

![screen shot 2016-05-25 at 12 10 39](https://cloud.githubusercontent.com/assets/19554486/15536248/cd81f2e8-2270-11e6-9717-d69c6045857d.png)

Thanks,

Marine

**Comment by bowhan** [comment]
Hi, Thanks for your interest. Unfortunately `piPipes`  doesn't work under Mac OS (this information is actually in the [main page](https://github.com/bowhan/piPipes#install)). With some tools (STAR for example) and genomes using a large amount of memory (>30G), Mac isn't a good choice anyway. 
With that said, if you still want to try it with smaller genome (like _dm3_), please use our [docker image]( https://hub.docker.com/r/bowhan/pipipes/)
I haven't rigorous test it under Mac OS. So if you have any questions, please post it here.

**Comment by mpetit75** [comment]
Hi,
Thanks for your (rapid) answer, I agree with you for the mac device but my lab have only mac computer. I will try with the docker (I am working on drosophila anyway).
