### ISSUE TITLE
Latest version of the genomes (danRer10)

### ISSUE THREAD

**Issue by naluru** [bowhan/piPipes#17]
Dear Dr.Han,

Thank you for providing a really nice pipeline for analyzing piRNA. Would it be possible to include the latest version of the zebrafish genome (danRer10, GRCz10)? I tried running piPipes with the version I installed and it is throwing error messages. 

Thank you,
Neel

**Comment by bowhan** [comment]
I have added danRer10 and very limited annotation files (I am not aware of any piRNA cluster annotation for this assembly, if you know, please let me know).
Can you give a try and let me know how it goes? The new code is sitting on its own branch called danRer10.
To access it, you need to do the following:
```
git fetch
git checkout danRer10
```
And then proceed with genome installation. 
If you encounter any error, please paste them here, thank you.
