### ISSUE TITLE
Bug in piPipes_bed2_to_bedGraph

### ISSUE THREAD

**Issue by yfu** [bowhan/piPipes#20]
Hi Bo,

It seems that this utility is handling the very first position in each contig in a weird way: the signals for the first positions are not set to 0 when a new contig is encountered. Below is an example:

```
$ cat small.ChromInfo.txt
NW_004581714.1	2150616
NW_004582652.1	6536

$ cat small.bed2
NW_004581714.1	0	1	1000	1	+	TCGCATGATCTTGGTGGCCAATT
NW_004582652.1	0	1	10	1	+	TTACGCAGAAAGCATTGTCTAGAT

$ ~/data/piPipes/bin/piPipes_bed2_to_bedGraph --input small.bed2 -c small.ChromInfo.txt -o small.output.
$ cat small.output.Watson.bedGraph 
NW_004581714.1	0	1	1000.00000
NW_004582652.1	0	1	1010.00000

```

The correct result should be
```
NW_004581714.1	0	1	1000.00000
NW_004582652.1	0	1	10.00000
```

There might be a bug in the bed2_bedgraph_converter function. This bug will not cause serious problems in relatively complete genome assemblies, such as dm3, and mm10, as they contain just a few contigs (chromosomes). However, this will cause some serious problems for fragmented genome assemblies, such as the silkworm genome assembly from NCBI.

Thanks!
Yu

**Comment by bowhan** [comment]
This is indeed a bug, which fails to initialize the signal for position 0 of the previous chromosome. It should have been fixed and the binary should have been updated. 
Thanks for reporting it Yu!
