### ISSUE TITLE
parameters in `/common/mm9/variables` 

### ISSUE THREAD

**Issue by dingailuma** [bowhan/piPipes#22]
Hi, Could you please give me an example of the parameters in `/common/hg19/variables` ? I'm a new starter and not very sure about the numbers I should use. Thank you so much !

**Comment by bowhan** [comment]
```bash
export rRNA_MM=2
export hairpin_MM=1
export genome_MM=1
export transposon_MM=3
export siRNA_bot=20
export siRNA_top=22
export piRNA_bot=23
export piRNA_top=35
```
