### ISSUE TITLE
Problems with R packages(ggplot2?)

### ISSUE THREAD

**Issue by tarcisiofbr** [bowhan/piPipes#24]
Dear Dr.Han,

I'm having troubles with what it seems to be related with R packages. When trying to run the pipeline I'm getting this warnings and some of the graphics on the output are strange.

```
Warning messages:
1: `axis.ticks.margin` is deprecated. Please set `margin` property  of `axis.text` instead 
2: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
3: `legend.margin` must be specified using `margin()`. For the old behavior use legend.spacing 
Error in read.table(file, FALSE) : no lines available in input
Calls: draw_smRNA_lendis -> read.table
Execution halted
```

I searched on the internet and it may be related with some updates in the ggplot2 package, but I'm not sure. I appreciate any help and thank you in advance for your attention.

Best Regards,
Tarcísio Brito

**Comment by bowhan** [comment]
The warning message regarding ggplot2 doesn't matter. What failed the run is `read.table` function, which complaints about the input file being empty. Is your library particularly small?

**Comment by tarcisiofbr** [comment]
Hi, sorry for the delay. After your answer I double checked the files and I think it was a problem while cutting the adaptors, but I already fix it and its not giving this error in `read.table` anymore. Thank you.

If you could, I just need a little help with one thing that I found strange on the output: a lot of the reads are aligning to the negative strand in the _flamenco_ cluster, as showed in the “.x_rRNA.piRNAcluster.pdf “ file(I’m using a already published _Drosophila_ library). The graphics on the output, in general, are very similar to the originial, but the output seems a little “noisy”. I was thinking that this may be caused by the piRNAs derived from the transposons(?). Do you know how can I fix that?

Again, thanks a lot and any help in this other issue I’ll already be thankful.

Bests,

Tarcísio B.

**Comment by bowhan** [comment]
I am not sure I understand the issue. I believe the majority of piRNAs in _Drosophila_ are derived from transposons, including and especially the ones in _flam_. But if you don't mind, you can send that pdf to `piPipesQ@gmail.com` and I will take a look to see if there is an issue.
