### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'   

### ISSUE THREAD

**Issue by dianalow** [bowhan/piPipes#6]
Hi, 

I keep getting this error during the mapping phase of the small RNA pipeline.

terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
(core dumped) piPipes_insertBed_to_bed2 $INPUT ${INSERT%.insert}.${GENOME}v${genome_MM}a.insert.bed > ${GENOME_ALLMAP_BED2}

could you help me out? thanks!

**Comment by bowhan** [comment]
Hi, 
It's the first time I saw this error.
The place where this error was thrown is not the first time piPipes_insertBed_to_bed2 is called. So I suspect that it might has something to do with some special sequences in your input.

If you can reproduce this error using a subset of your fastq file, do you mind to send me (bo.han`at` umassmed.edu) that? Also let me which genome it is.

Thanks and sorry for the inconvenience, 
Bo
