### ISSUE TITLE
Errors while installing R dependencies

### ISSUE THREAD

**Issue by blaiseli** [bowhan/piPipes#7]
Dear Bo Han,

I get the following errors when running piPipes install -g dm3 -c $(nproc):

```
ERROR: dependencies ‘plyr’, ‘reshape2’, ‘scales’ are not available for package ‘ggplot2’
* removing ‘/home/bli/src/piPipes/Rlib/ggplot2’
ERROR: dependencies ‘ggplot2’, ‘scales’ are not available for package ‘Hmisc’
* removing ‘/home/bli/src/piPipes/Rlib/Hmisc’

The downloaded source packages are in
	‘/tmp/Rtmp7KPCan/downloaded_packages’
Loading required package: ggplot2
Error in pkgTest("ggplot2") : 
  Failed to install the package. Please check the internet access or update your R if it is too old.
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ggplot2’
2: In install.packages(x, dep = TRUE, lib = paste(Sys.getenv("PIPELINE_DIRECTORY"),  :
  installation of package ‘reshape2’ had non-zero exit status
3: In install.packages(x, dep = TRUE, lib = paste(Sys.getenv("PIPELINE_DIRECTORY"),  :
  installation of package ‘scales’ had non-zero exit status
4: In install.packages(x, dep = TRUE, lib = paste(Sys.getenv("PIPELINE_DIRECTORY"),  :
  installation of package ‘ggplot2’ had non-zero exit status
5: In install.packages(x, dep = TRUE, lib = paste(Sys.getenv("PIPELINE_DIRECTORY"),  :
  installation of package ‘Hmisc’ had non-zero exit status
6: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ggplot2’
Execution halted
[2015-07-03 16:51:41 CEST] Downloading iGenome dm3
```

(It then continues downloading dm3 genome)

My version of R is 3.0.2 (It's the one packaged in Ubuntu 14.04 http://packages.ubuntu.com/fr/trusty/r-base-core). Could it be too old ?

Other remarks:

- Later I get a bunch of warnings:
WARNING. chromosome (chrUextra) was not found in the FASTA file. Skipping.
Just before
[2015-07-03 17:09:14 CEST] Building STAR index for genome

- I noticed a typo in the configuration questions: "trasnposons" on line 159 of `bin/piPipes_install_genomes.sh`

**Comment by bowhan** [comment]
Thanks for reporting the issue. 
Can you please try to install the R packages (ggplot2 for example) manually under the interactively interface? Please do it with ```install.packages``` with the ```option lib="/home/bli/src/piPipes/Rlib"```
If you cannot successfully install it, there might be issues with the R or the system. 
If you can, please manually install the following packages:

ggplot2
ggthemes
gplots
parallel
scales
reshape
gridExtra
RColorBrewer
gdata
labeling
RCircos

As to the warning, please ignore ```chrUextra``` since we don't use it, even though some annotation includes stuff there.

**Comment by blaiseli** [comment]
Manual installation also fails:

```
> install.packages("ggplot2", lib="/home/bli/src/piPipes/Rlib")
--- Please select a CRAN mirror for use in this session ---
Warning: dependency ‘plyr’ is not available
also installing the dependencies ‘reshape2’, ‘scales’

trying URL 'http://mirrors.softliste.de/cran/src/contrib/reshape2_1.4.1.tar.gz'
Content type 'application/x-gzip' length 34693 bytes (33 Kb)
opened URL
==================================================
downloaded 33 Kb

trying URL 'http://mirrors.softliste.de/cran/src/contrib/scales_0.2.5.tar.gz'
Content type 'application/x-gzip' length 56346 bytes (55 Kb)
opened URL
==================================================
downloaded 55 Kb

trying URL 'http://mirrors.softliste.de/cran/src/contrib/ggplot2_1.0.1.tar.gz'
Content type 'application/x-gzip' length 2351203 bytes (2.2 Mb)
opened URL
==================================================
downloaded 2.2 Mb

ERROR: dependency ‘plyr’ is not available for package ‘reshape2’
* removing ‘/home/bli/src/piPipes/Rlib/reshape2’
ERROR: dependency ‘plyr’ is not available for package ‘scales’
* removing ‘/home/bli/src/piPipes/Rlib/scales’
ERROR: dependencies ‘plyr’, ‘reshape2’, ‘scales’ are not available for package ‘ggplot2’
* removing ‘/home/bli/src/piPipes/Rlib/ggplot2’

The downloaded source packages are in
	‘/tmp/RtmpBLd6xq/downloaded_packages’
Warning messages:
1: In install.packages("ggplot2", lib = "/home/bli/src/piPipes/Rlib") :
  installation of package ‘reshape2’ had non-zero exit status
2: In install.packages("ggplot2", lib = "/home/bli/src/piPipes/Rlib") :
  installation of package ‘scales’ had non-zero exit status
3: In install.packages("ggplot2", lib = "/home/bli/src/piPipes/Rlib") :
  installation of package ‘ggplot2’ had non-zero exit status
```

It seems thas some of the R packages used by piPipes are simply not available for the R version shipped with Ubuntu 14.04. For instance, <http://cran.r-project.org/web/packages/plyr/index.html> says that package `plyr` version 1.8.3 needs R version 3.1.0 or above. I don't know if earlier versions are supposed to be available for R 3.0.2

**Comment by bowhan** [comment]
I see. Seems ```plyr``` is the reason why it failed. 
Please upgrade your R to the newest version then. 
Thanks for reporting this!

**Comment by blaiseli** [comment]
It seems that the packages with the correct version are available through `apt-get`.
The following to commands enabled  me to then install `gplot2` and the other packages on your list from within R:
```
sudo apt-get install r-cran-plyr
sudo apt-get install r-cran-reshape2
```

A concern I frequently have is the following: is it better to use a language's integrated package installation mechanism or the system-wide package manager?
I used to see the second way of doing "cleaner", and usually use it for python packages.
In the case of perl, I frequently find it hard to identify the correct Ubuntu/Debian package name.

**Comment by bowhan** [comment]
I always use the first one simply because I don't have admin permission :-)

**Comment by EricPeter** [comment]
installation of package ‘httpuv’ had non-zero exit status
ERROR: dependencies ‘httpuv’, ‘mime’, ‘jsonlite’, ‘digest’, ‘htmltools’, ‘sourcetools’, ‘later’, ‘promises’, ‘rlang’ are not available for package ‘shiny’
* removing ‘/home/EricPeter/R/x86_64-redhat-linux-gnu-library/3.5/shiny’
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status

**Comment by blaiseli** [comment]
@EricPeter I recently had similar problems with R packages that were apparently due to the version of gcc. In my case, a solution consited in using gcc version 4.9, R 3.5 and bioconductor to install packages.

**Comment by EricPeter** [comment]
So did when you changed the gcc version or upgraded it worked
